language: python

# test a few python versions
python:
  - 3.6
  - 3.7
  - 3.8

# ubuntu bionic (18.04)
os: linux
dist: bionic

# pre-install commands
before_install:
  - python3 --version
  - pip3 install --upgrade pip
  - pip3 install --upgrade pytest

# no dependencies
install: skip

# run tests
script: pytest

# before deployment, update setuptools and wheel
before_deploy:
  - pip3 install --upgrade setuptools
  - pip3 install --upgrade wheel

# conditional deployment
deploy:
  # deploy to test pypi index only if DEPLOY_DRY file is present
  - provider: pypi
    username: __token__
    password:
      secure: Po8a1vIv1lCqmxwrToP4oa/Im42j/ZdCPOqyhJRVVFNvRCLqXYBwat9l8Y2vPxG3uxSEjctddssqiVt4DUvGHzPu0gbF9JCA9Sj41ZDp7ozThQEULhWxlWv1ZRFDOB6/BWYHv3FcEL7teW1c64ldVd4hTa3FA6HIgP4FiQuITljxEZV9OCYV8YNiM3v9PZg0OtU5uowgfx/4Oxh85xN/3lC2BIOnQTD+go+THH6PF1h25bagIeFpZTw2hVvj4BHc1ako7nRyPQYf59x4oL/ZTNifEByNfvBGDjuEFIC7V2PH3CWHUSjbHeKrmZpbEPDO1V/At2QI0BnWdCyzEiDOiI2CrQlImqopsy5jCxQDUiThIgMnbc48AqWbXg1WlsHXffaGXQbtAzbfsA3ElyEQWfAse8JWmC4g/SPs1aO+9IiQRiAtrPXzSZab/1u5xN+w2axrAqzTjF/SrMBgyyL+MQyxu+++KGfI9ASxcGLJt3oILyqbVtgvOBmHrmWed1g/nxjjQkohKHuFLaTvnBPczOR0pxdvHbn5PYb+YXqTeVdgKWEymSbGhob1g+rs2gJB6vQZ1FTOKyq1r9QQQik4KrNHJortGBSnyGTgTYgrh+qLJSstbgBOdsSyuixliTRBlcaoUxdiZxkxGPUkTIzkK/oXMyHY8dDhPWYCx9tjPc4=
    server: https://test.pypi.org/legacy/
    distributions: sdist bdist_wheel
    skip_existing: true
    on:
      condition: -e DEPLOY_DRY
  # deploy to actual pypi index only if DEPLOY_WET file is present
  - provider: pypi
    username: __token__
    password:
      secure: Bgc/LnhaYzNJ6VUndOoOZFVIvAJ2fqpyRBBJY6RphqHL1MhUHHm/fkDNcUkQAlDtPE8HVeZDd5XuK33LSeRlCRF/9bstNxt1xPtFxISCvGbVc0maTdSMtJBsLehBmvSCzvPHO78Mz1KnEv/oISkAFxd3pBYoiS2SCjXUkM6cfTQhNqRTFTStX4XagVVZL91iiV3k8GpDGxnNjJP3sU3fOr+vmFlWAolbfBQHCErfBFW0ZLlixhKCLhnNLaRJuabGKcEq/Hg9BSDx0cPm1zgbe/fHZxAoqD6mfjmNiyCprz4Do796ov348it3XTGGq/oPe4vd4fMPU54sheX6xxBiLyxj8UBa/4gf3kqPMUti5qfQUPoabLY21go7blWmkSvbWX3yreLQrvrk4iONViC7w5Vi0aYon6n4J77IPqqpGrGNZOvZHpHwxXrOc5q45kULhF+KR2wbsX5lTvm4hq2/x5s5U7d7ljliIIewOLEMtOFzF9fGwmAbvqOZFyk64Oteexc7tjxPy73Dd7oFmv+NzqVqzZZJTajslhuMYrYxLIvwh3mPVBGYFCCMVS8c13WmnZ1sD3rtHkkrFgQCHsEl9M7XPZAfohiCy4RZIRnKmPqkOF3dvT4fJ2NIUUlOM0HnUrZHhdIH5ZnKAV2ZcO+0qAg5lvSUyUn9V/oXQSVOj+w=
    distributions: sdist bdist_wheel
    skip_existing: true
    on:
      condition: -e DEPLOY_WET
