language: python

# test a few python versions
python:
  - 3.6
  - 3.7
  - 3.8

# ubuntu bionic (18.04)
os: linux
dist: bionic

# pre-install commands
before_install:
  - python3 --version
  - pip3 install --upgrade pip
  - pip3 install --upgrade pytest

# no dependencies
install: skip

# run tests
script: pytest

# conditional deployment
deploy:
  # deploy to test pypi index only if DEPLOY_DRY file is present
  - provider: pypi
    username: __token__
    password:
      secure: IIygJpFP7xO/7GqC37lowl/GPbx4wRPMBdoz6gFUBrSe55uQXmB6JI4b6b02SEqVyhvHEYehI1ymQh7Ln5yoDQg4cEGtbfZJdoZDb0/2fQEek6+/HtbtxlEq/236pIG7rti3Wup12kAvtB5ObKfXPjK8r0Bz3rTnJ1uNMCB1iQ7umBsiSCoJWQziKCT+/UTlcz5fjOJgQODyW8mufz+Dfv4NAJKCUFiXrG14xpzpJc6LRWeX+NatpSgMCfJJ12bJyeZIGQ5JnugvsGbvUGfoIad47/Fftf91l5wKP/Lejwwet5tGb+RZiQ2dClQU9nZueVa6NDSA22PbbGP1wWz/ZAPt0GXaK5RnAb+w/xFIsVmOpou/0ZdemJfHE6KZFAuImB3Wnsqsxw9fj9a62qG9GqE3ToOx96mljGUcNelfi8w37qXT3FhE6WijbV3ApRuP0DRzG52wsZTWxdxg7vFgJ2e0ofIOzUlV6zg5RyQEnSO+NFFGloros9hlteuidwG0z/EVNtGnqK5ryu5chbHZMPewzzUcu3FTGod60CxfaqAkUsyDop9hXD/qKSJkf7cqsvUuDQRutfA6cxQZN33wcY9X+i02GF+8wdQJ0zVtg89QNhgP7QOptPOv9ILcdyyA8na8LBDwjvC6EqjeLp0c0+wwOOOBhbWH50Ac6EkbA1k=
    server: https://test.pypi.org/legacy/
    distributions: sdist bdist_wheel
    skip_existing: true
    on:
      condition: -e DEPLOY_DRY
  # deploy to actual pypi index only if DEPLOY_WET file is present
  - provider: pypi
    username: __token__
    password:
      secure: A7Dqcy2Wpx5dGAOfwW7mXBZ1DUQmvnpFI2g+Uk5RlSnfCjVeeAIPFvn7P1LBacnDWu14tI6hA4IzSqI9mZ022GuOOApU2o57bsyDZd+DXABsH8Z3zuxM2xgdEIwxErEfrMykvAucacyopKRkEkVsbBBDj0jNiy2Ozv/JUhzqDQw5EyovP6Dn2TrfJTlRlhWjkI6RoVLBcNj/nKdcburzvzXNfr5Nfq0w4ViBVleGYefrG2yExs+WgAS/Raiqtc/rUH23r1FlzkssCcbqxbuMNXI8zo0pI58k28DeA7e3yqhKwchIutp4fJaA9PqaRi/5JT33NG+M5XcI+Z3g/Pa5k5w75oiEJw5Ug3Q4evaAZNFwJINRN+a0ilipFwciyz8nUdzo3Bn7P9/YiQzI66DKQCJ+C/RLbTJWOm+34+Em9xrH2LasnDqzo0GljFRbe+xTge0wEQysk35mG/2lt6Djg4q18Ai0hstrckZYDbULi15zJ/9POzun/Oe+mwfs2X3y85uVSCqyicZirJwbIZYJXodK55s8uKwuPb6MzkhV9n1RxWQ60zsYQ+EIcHBHX7zI2gklqfMutrH+F2RWqaQSnaY8XLEsVurj0voKFg4PFY+1OB+987NLpkZP6Hmn4l1M95RNWdfXzW/UTeVWAs02UtPebQTtcy2gOAhm7+IcGQs=
    distributions: sdist bdist_wheel
    skip_existing: true
    on:
      condition: -e DEPLOY_WET
