language: python

# test a few python versions
python:
  - 3.6
  - 3.7
  - 3.8

# ubuntu bionic (18.04)
dist: bionic

# pre-install commands
before_install:
  - python3 --version
  - pip3 install --upgrade pip
  - pip3 install --upgrade pytest

# install with setup.py (not on PyPI yet)
# looks scary, but is really python3 setup.py install in venv
install: make root_install

# run tests
script: pytest