language: python

# test a few python versions
python:
  - 3.6
  - 3.7
  - 3.8

# ubuntu bionic (18.04)
dist: bionic

# pre-install commands
before_install:
  - python3 --version
  - pip3 install --upgrade pip
  - pip3 install --upgrade pytest

# install with setup.py
# by default, this is a root install [into a venv]
install: make install

# run tests
script: pytest

# deploy to test pypi index only if DEPLOY file is present
deploy:
  provider: pypi
  username: __token__
  password:
    secure: IIygJpFP7xO/7GqC37lowl/GPbx4wRPMBdoz6gFUBrSe55uQXmB6JI4b6b02SEqVyhvHEYehI1ymQh7Ln5yoDQg4cEGtbfZJdoZDb0/2fQEek6+/HtbtxlEq/236pIG7rti3Wup12kAvtB5ObKfXPjK8r0Bz3rTnJ1uNMCB1iQ7umBsiSCoJWQziKCT+/UTlcz5fjOJgQODyW8mufz+Dfv4NAJKCUFiXrG14xpzpJc6LRWeX+NatpSgMCfJJ12bJyeZIGQ5JnugvsGbvUGfoIad47/Fftf91l5wKP/Lejwwet5tGb+RZiQ2dClQU9nZueVa6NDSA22PbbGP1wWz/ZAPt0GXaK5RnAb+w/xFIsVmOpou/0ZdemJfHE6KZFAuImB3Wnsqsxw9fj9a62qG9GqE3ToOx96mljGUcNelfi8w37qXT3FhE6WijbV3ApRuP0DRzG52wsZTWxdxg7vFgJ2e0ofIOzUlV6zg5RyQEnSO+NFFGloros9hlteuidwG0z/EVNtGnqK5ryu5chbHZMPewzzUcu3FTGod60CxfaqAkUsyDop9hXD/qKSJkf7cqsvUuDQRutfA6cxQZN33wcY9X+i02GF+8wdQJ0zVtg89QNhgP7QOptPOv9ILcdyyA8na8LBDwjvC6EqjeLp0c0+wwOOOBhbWH50Ac6EkbA1k=
  server: https://test.pypi.org/legacy/
  distributions: sdist bdist_wheel
  on:
    condition: -e DEPLOY
  skip_existing: true