language: python

# test a few python versions
python:
  - 3.6
  - 3.7
  - 3.8

# ubuntu bionic (18.04)
dist: bionic

# pre-install commands
before_install:
  - python3 --version
  - pip3 install --upgrade pip
  - pip3 install --upgrade pytest

# install with setup.py
# by default, this is a root install [into a venv]
install: make install

# run tests
script: pytest

# deploy to test pypi index
deploy:
  provider: pypi
  username: __token__
  password:
    secure: pypi-AgENdGVzdC5weXBpLm9yZwIkZTExMGUzOGMtZjRmNS00MDBjLTkwNzQtZGI4YTNhNTQzMWMzAAIleyJwZXJtaXNzaW9ucyI6ICJ1c2VyIiwgInZlcnNpb24iOiAxfQAABiB4w3dl3EcXZerr2uvl1j4MHsAUR40ozeKQtsqcI52VcQ
  server: https://test.pypi.org/legacy/
  distributions: sdist bdist_wheel
  skip_existing: true