# this is also displayed in the status badge, so it is a bit uninformative
name: build

on: push

jobs:
  # run unit tests
  test:
    # maybe add more OSes later?
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        # python versions to use during python setup
        python_version: [3.6, 3.8]
    steps:
    # need to checkout repo so that we have access to $GITHUB_WORKSPACE and also
    # set up the specific python version that we are testing the code with
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: Echo Python version + upgrade pip and pytest
      run: |
        python3 --version
        pip3 install --upgrade pip
        pip3 install --upgrade pytest
    - name: Run unit tests with pytest
      run: pytest