# this is also displayed in the status badge, so it is a bit uninformative
name: build

on: push

jobs:
  # run unit tests
  test:
    # maybe add more OSes later?
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python versions to use during python setup
        # note: need to keep bumping this as runners evolve
        python_version: [3.9, 3.12, 3.13]
    # matrix job name
    name: CI build (Python ${{ matrix.python_version }})
    steps:
    # need to checkout repo so that we have access to $GITHUB_WORKSPACE and also
    # set up the specific python version that we are testing the code with
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python_version }}
    - name: Echo Python version + upgrade pip and pytest
      run: |
        python --version
        pip install --upgrade pip
        pip install --upgrade pytest
    - name: Run unit tests with pytest
      run: pytest
