# deploy to test PyPI for test purposes
name: test_deploy

on: workflow_dispatch

jobs:
  # deploy only after unit tests have all been passed!
  test_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      # note: Python version doesn't matter (package is pure Python)
      with:
        python-version: 3.13
    - name: Echo Python version + upgrade pip, setuptools, wheel, twine
      run: |
        python --version
        pip install --upgrade pip
        pip install --upgrade setuptools wheel twine
    - name: Create source and binary distributions using setup.py
      # note: setup.py deprecated
      run: python setup.py sdist bdist_wheel
    # since skip_existing is false by default, remember to bump versions!
    - name: Upload source and binary distributions to Test PyPI
      uses: pypa/gh-action-pypi-publish@v1.13.0
      with:
        user: __token__
        password: ${{ secrets.LOCAL_TESTPYPI_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
